spring:
  mvc:
   view:
    prefix: /pages/
    suffix: .jsp
  datasource: 
   url: jdbc:mysql://localhost:3306/metacubeparkingspring
   username: root
   password: root 
   driver: com.mysql.jdbc.Driver


